webtalk_init -webtalk_dir /home/andreaalf/VivadoProjects/ProgettoRetiLogiche/ProgettoRetiLogiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 27 08:42:02 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "79ddde6e-8158-4bd9-8173-6a17e4eeafcf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aaf04dc26ce54be19a5dab849a674668" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6198DU CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.311 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1002 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "299 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "8524" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "471" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.84_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "361640_KB" -context "xsim\\usage"
webtalk_transmit -clientid 734101629 -regid "" -xml /home/andreaalf/VivadoProjects/ProgettoRetiLogiche/ProgettoRetiLogiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/andreaalf/VivadoProjects/ProgettoRetiLogiche/ProgettoRetiLogiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/andreaalf/VivadoProjects/ProgettoRetiLogiche/ProgettoRetiLogiche.sim/sim_1/synth/timing/xsim/xsim.dir/project_tb_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
